update: image.c

image.c: ../src/xml2pmx.x preload
	./preload $< >$@

../src/xml2pmx.x: force
	$(MAKE) -C $(@D) $(@F)

preload: preload.o
	gcc $(CFLAGS) $^ -o $@

CC = gcc
CFLAGS = -I ..

pristine: force
	rm -f $(SOURCE) image.c

force:
